### ISSUE TITLE
Error at startup: Cannot find module 'hoek'

### ISSUE THREAD

**Issue by gouroujo** [mattkrick/meatier#102]
Hi,
Thanks for your amazing project.
I have some trouble to run the project on my mac. It run perfectly just after `npm install` but now it's broken even after `git reset HEAD --hard`
I've got the following error:

> npm start

> meatier@0.9.0 start /Users/jonathanpollak/Sites/meatier
> NODE_ENV=development node ./src/server/server.babel.js

>   [Busy] Launching SocketCluster
>    Broker PID: 11041
>1456674756841 - Origin: Worker (PID 11044)
>   [Error] Error: Cannot find module 'hoek'

Moreover, I can't run `transpileJoi.sh` due to either:
- babel not found (missing dependencie in package.json, it's recommanded to install it locally)
- node_modules/joi/lib doesn't exist

What is the purpose of this bash script?

Running `npm install hoek` solve the issue

**Comment by gouroujo** [comment]
removing the `nodes_module` folder and start a new install solve the problem but this part seems to be not enough stable

**Comment by mattkrick** [comment]
you can ignore the bash, it's for advanced, undocumented use cases. if your node_modules isn't empty, that's on you, since moving from npm2 to npm3 could bork it, etc. as long as you follow the directions exactly as they're laid out in the readme, everything should work perfectly. if not feel free to reopen!
