### ISSUE TITLE
Wishlist feature: server hot-reload

### ISSUE THREAD

**Issue by wmertens** [mattkrick/meatier#115]
See http://jlongster.com/Backend-Apps-with-Webpack--Part-III - being able to hot reload the graphql handlers without losing connections to databases etc sounds like it would make meatier SUPER AWESOME :hamburger: :fire:

**Comment by mattkrick** [comment]
honestly, i don't see too much value in this, but I'm definitely open to being proven wrong.

The cost is replacing piping with nodemon, add in another webpack config (for a total of 4), and then it still won't work with any side effects (including starting/restarting the http and ws servers), which means when it doesn't act as expected, you have to do a manual restart, which will take even longer since it has to run through a webpack build. you'll also probably want a 2nd babel config so you don't waste build time on doing things that node already does natively (eg let/const).

The benefit is the time it takes to restart the server & connect to the DB, which currently takes about 3-4 second on a 2013 MBA using piping to automatically restart on file change. if 50% of your changes are side effect free, you're essentially at a coin flip: heads you save 2 seconds, tails you lose 5 + the time it takes you figure out it was tails... and every time you start your server, you also lose 5. 

i don't mean to sound pessimistic at all, as HMR is very cool tech & is just now in its infancy, but I just don't think it's ready to be adopted for this use case. i love being proved wrong though :smile:

**Comment by wenzowski** [comment]
> tails you lose 5 + the time it takes you figure out it was tails

ow. :point_up_2:

**Comment by wmertens** [comment]
@mattkrick I just thought of a use case: hot-reloading server-side prerendering! That way you can debug initial page loading .

It would in theory be possible to load the react client as a regular module via webpack and then to perform HMR like in the browser. I tried briefly in another project to load the entire app via webpack but that choked on the node modules. Perhaps the code could instead be loaded via the webpack dev server.

Jspm should in theory be able to store the intermediate build products for quick restarts.

Perhaps it's not quite possible with the current state of loaders.

**Comment by mattkrick** [comment]
@wmertens could you elaborate? why do you need the react client? wouldn't you still be loading a webpack dev server that then loads your actual server?

**Comment by jeffreywescott** [comment]
A nice compromise is to just hot-reload the Express routes. [See here](https://github.com/glenjamin/ultimate-hot-reloading-example).

Piping is a shit-show when combined with webpack hot module reload, because it forces webpack recompilation every time the server restarts.

**Comment by mattkrick** [comment]
@jeffreywescott totally agree, that's why i always use the production setup when i edit the server (with piping always turned on). That way, when your server restarts, you just grab the pre-built client bundle instead of recompiling it. The only pain point left is when you're troubleshooting a server-side-only bug in a component, as that needs a new client bundle & requires a server restart. Chances are those are gonna be pretty infrequent though.

**Comment by wmertens** [comment]
Ok, so elaboration time:

* Suppose you load the entire server the way the client is loaded
  * This means that you get the same loader results, e.g. URLs for images, objects for css-modules, code for javascript
  * This means you can run client code and it will get the same results => prerendering
  * This means you don't need to create a bundle first
* Now add hot reloading to the mix
  * If the module is hot-reloadable, do so, otherwise die and let a wrapper restart the app
  * The next client prerender or API call will use the new code, but the database connections will persist
* If the loader can store and reference built modules, restarts are fast

I couldn't get Webpack to work because I couldn't convince it to leave requires of node_modules alone, but maybe it can be done.

JSPM 0.17 should be able to do it, since that is a loader first and a bundler second, and they are at least planning to store build results keyed by input hash.

As an aside, NixOS.org is a Linux distribution based on storing packages immutably under their input hash (source, build scripts, compiler, flags, …), and generally it takes only a few seconds to create a new version of the entire OS when you change some setting. In other words, caching load results based on a hash of their loader and the input source should lead to super fast restarts.

**Comment by mattkrick** [comment]
@wmertens you'll still need a client-only bundle since you've got client-only logic (eg `localStorage`). 

to leave node_modules alone, just add an exclude for regex `/node_modules/`. I still can't grok how the whole thing would work but if you've got the vision i'm happy to help where i can.

**Comment by wmertens** [comment]
Yes, the client still needs its own bundle, but the server should just load its dependencies on the fly.

The exclude is not as simple as that, is it? Webpack should convert imports and requires of node_modules into requires that are retained in the code and don't use the webpack require function…

**Comment by mattkrick** [comment]
K, I'm missing something. If we bundle up the whole server with webpack how can it grab dependencies on the fly? Webpack would walk the ast, grab the dependencies, and bundle them all together, right?

**Comment by wmertens** [comment]
The bundling feature of webpack it unnecessary, the only thing needed is the loader so that it gets the same deps as the client for server side rendering. The regular node modules should be loaded by node, because binary modules can't be bundled, and besides it takes ages to build…

**Comment by mattkrick** [comment]
but you have to bundle. Otherwise, it'd break on the first non `.js` require.

**Comment by wmertens** [comment]
Well, https://github.com/ericclemmons/webpack-hot-server-example got there before me :)

![server hmr](https://github.com/ericclemmons/webpack-hot-server-example/raw/master/hmr.gif)

**Comment by mattkrick** [comment]
😳  im cautiously, super excitedly, optimistic. i'm wondering what the edge cases are. if it can do this reliably, and with web socket servers, then this is definitely a game changer.

**Comment by wmertens** [comment]
Looking at it, it's a straight-up application of HMR. Webpack runs in watch mode with HMR, and there is a plugin that runs the result as soon as it is available. Then when a module updates, it is replaced and on an incoming request Express ends up calling the new one.

So yes, I don't see why it shouldn't work with websockets!

There's even a plugin that automatically installs NPM dependencies 😆  Awesome job @ericlemmons! 🎉
