### ISSUE TITLE
Wishlist: Otto

### ISSUE THREAD

**Issue by ktmn** [mattkrick/meatier#117]
I got all sorts of problems trying to run meatier on Windows. Problems that want me to install Visual Studio, Dev kits, .NET stuff and god knows what else. Needless to say I turned to Otto (https://github.com/hashicorp/otto) which would create a virtual dev environment using Vagrant, Docker and whatnot, all with a couple simple commands.
Unfortunately it doesn't work with Meatier out the box and needs a conf file "Appfile". So here's what I got so far

```
application {
	name = "meatier"
	type = "node"

	dependency {
		source = "github.com/soplakanets/otto-rethinkdb"
	}
}

/*customization "docker" {
	run_args = "-p 8080:8080"
}*/
```

The last part is commented out, because it doesn't work. I don't quite know how the rethinkdb dependancy works, is the database started automatically? I think it forwards the 3 rethinkdb ports to the dev environments vm, but I don't know how to get the 8080 forwarded from dev vm to host, so I could actually reach the rethinkdb admin interface.

So I'm posting this here, maybe someone smarter than me can finish the Appfile and make Meatier work with Otto. That would be so convenient.

Potentially Otto could also handle building and deploying to AWS with a single command, but that's something way over my head.

**Comment by mattkrick** [comment]
There's a few folks devving on windows and I don't think they ever needed
anything like Otto. If you're developing, you'll need those frameworks,
it's kinda unavoidable I think, it's like command line tools in OSX. If I
were you, I'd put mint or Debian on a separate partition and dev on
something closer to your deploy environment. I'm not really keen on configs
that are windows specific because I don't have or want windows and can't
imagine anyone deploying in a windows environment, but any small changes to
work with windows are always accepted.

**Comment by ktmn** [comment]
>  I'm not really keen on configs that are windows specific

Yeah that's why having a (working) Appfile would be ideal in my opinion since Otto is cross platform. The whole process of getting up and running would be the same on every system:

git clone github.com/.../meatier
cd meatier
otto compile *(reads the settings from Appfile)*
otto dev *(makes vm for meatier and vm for db and/or magic)*
otto dev ssh *(ssh into vm)*
npm install
npm run quickstart

About the Windows thing, it (bcrypt library) want's me to install Windows SDK, which asks me to install .NET 4, but when I try to install .NET 4 I get a message saying I already have it as part of the OS, so... yeah, I kind of called it quits there.

**Comment by emreeren** [comment]
I tested it with windows 10 with these changes and it worked fine.

- Installed RethinkDB Alpha 6 version https://github.com/rethinkdb/rethinkdb/issues/5389#issuecomment-185390638
- Installed Python 2.7.11 for bcrypt library. https://www.python.org/downloads/ (3.x does not work). 
- Edited environment variables to add Python path. http://stackoverflow.com/questions/6318156/adding-python-path-on-windows-7
- Modified package.json scripts as shown here. http://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json-node-js (See comments for accepted answer)

I already had Visual Studio installed so I didn't see any errors related with Windows SDK or .Net framework.

**Comment by ktmn** [comment]
Oh I just discovered that something similar is already in use at https://github.com/r3stack/r3stack - azk. Never heard of it but it seems to try to solve similar problems as Otto. Seems to have a really bloated conf file already tbh, but I'll give it a go some time.

**Comment by Bartekus** [comment]
@ktmn 
The reason why the config is bloated is due to the fact that each aspect of the build can be independently configured and also because it include builds for deployment and database. However the fact that it's entirely written in js and has great potential due to use of docker as its fundament should be a convincing reason to give it a go.
