### ISSUE TITLE
xo does weird globbing

### ISSUE THREAD

**Issue by wenzowski** [mattkrick/meatier#122]
I'm guessing we meant to [lint the entire src folder](https://github.com/mattkrick/meatier/blob/master/package.json#L24). This doesn't do that.

Perhaps `rm -rf build && xo --fix` would be a better choice?

**Comment by mattkrick** [comment]
haha i noticed that a couple days ago when i saw a stray `var` declared. any idea on why it's not working? if it's a bug, we should report it, i'm hesitant to rimraf the build just because the 3 builds can take around 30 seconds so that gets painful. Usually when I lint i usually mess up & do more than just lint or work from the top of the file down & screw up the line numbers so bad that i have to recompile, make sure i didnt bork it, then re-run the linter.

**Comment by wenzowski** [comment]
not sure if this is intended upstream behaviour

Yes, though accidentally running `xo --fix` without removing the build folder is more so: it doesn't seem to respond to interrupt so you have to `kill -9` it or cook some eggs.

I got around it by moving linting to CI.

**Comment by wenzowski** [comment]
This will be closed automatically by merge of #125
