### ISSUE TITLE
consider using webpack-merge to simplify webpack config

### ISSUE THREAD

**Issue by jedwards1211** [mattkrick/meatier#155]
just a tip...https://www.npmjs.com/package/webpack-merge

**Comment by mattkrick** [comment]
As a personal preference, I like webpack configs to be as big & verbose & easy to read as possible. Back in the day I read every single webpack config on github to arrive at the current setup & the biggest thing I learned from the exercise was that folks who tried to be cute & save a few lines of code had really difficult-to-grok configs (https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js). Size is irrelevant since it'll never make it to the client, but comprehension is critical since webpack is freaking complicated. The only benefit is _maybe_ not having to repeat the change in 1 other place, but then again, it could mean you have to refactor something out of the base config & into an environmental config, which means you're at a net loss compared to separate dumb configs.
