### ISSUE TITLE
What is: "Goes Oprah-Christmas-special with websockets"? 

### ISSUE THREAD

**Issue by faceyspacey** [mattkrick/meatier#3]

**Comment by mattkrick** [comment]
everybody gets one: https://youtu.be/XcI-rHO0yko?t=31s

This isn't great because realistically, only part of your app needs a websocket. For example, let's say you have a SAAS & only 10% of visitors actually sign up or log in. Why give a websocket to the 90% that are just browsing the landing page? With Meteor, the way to avoid this is to create a completely separate, non-meteor app *just for your landing page.*

**Comment by faceyspacey** [comment]
gotchu. whats ur plans for this?

**Comment by mattkrick** [comment]
I'm using this as a boilerplate for a large-ish project I'm working on right now. I think it's a pretty solid design pattern so I wanted to abstract it out & open source to get some feedback. Next steps would be boilerplating the whole auth workflow (forgetten password, email verification) creating a webpack config with `target: 'node'` so it can process CSS & images for SSR, and then a webpack production build to showcase code splitting, vendor chunking, common chunks, etc.
