### ISSUE TITLE
RPC functionality

### ISSUE THREAD

**Issue by abastardi** [mattkrick/meatier#40]
Have you considered adding RPC functionality, similar to Meteor methods?

Also, have you looked at [deepstream.io](http://deepstream.io/) as a possible alternative to SocketCluster? It appears to include an RPC mechanism as well as integration with RethinkDB.

**Comment by mattkrick** [comment]
Thanks for this, client-side caching/realtime data fetching is probably the fastest moving area of the JS ecosystem, and where the JS community has chosen some clear winners in other areas (react for frontend, webpack for building, etc.) The data/transport layer is still the wild west & I'd love a list of things like deepstream to compare and see if there's a clear winner. If you know of any other services like this one send em my way so we can compare & pick the best.

My ideal solution would:
- allow for offline-first (via serviceWorkers)
- use websockets that scale vertically (and horizontally with a MQ like redis or rabbitmq)
- plug into a redux store (no one does this yet)
- use webWorkers to keep the UI snappy
- use graphQL (facebook uses event-driven subscriptions instead of websockets, so this is gonna have to come from the community)

RethinkDB is coming out with something on the client, which I'm really excited about, although that would kill the whole "client is database agnostic" approach that I've got going on right now.

**Comment by abastardi** [comment]
Thanks for the reply. Sounds like some great ideas.

I'll keep an eye out. So far, deepstream is the only thing I've seen that seems somewhat comparable to SocketCluster (the deepstream Github repo hasn't been too active recently, but they have [announced](http://deepstream.io/blog/introducing-deepstreamhub/) that they're working on a hosted platform). Regarding RPC specifically, it appears [avs-rpc](https://github.com/gigerlin/rpc) supports SocketCluster.

> RethinkDB is coming out with something on the client, which I'm really excited about, although that would kill the whole "client is database agnostic" approach that I've got going on right now.

Yes, I read about their plans -- interested to see what they come up with (according to their timeline, should be soon). It sounded like they eventually hope to support graphQL as well.

**Comment by niallobrien** [comment]
Anyone got any further info on what RethinkDB are coming out with exactly & when? Thanks.

**Comment by mattkrick** [comment]
From my understanding it's a package allowing you to write something like
`r..insert` directly from the client, and will later be pluggable into
graphql, but I'm not in the beta group so I don't know any details. I'm
slowly rewriting meatier using graphql and it's already pretty painless, so
I'm not sure what they're gonna improve unless they offer a really
intelligent client side cache

**Comment by niallobrien** [comment]
Thanks @mattkrick - I know they mentioned the fact that they weren't overly happy that the GraphQL spec wasn't fully where they'd like it to be.

**Comment by abastardi** [comment]
> Anyone got any further info on what RethinkDB are coming out with exactly & when? Thanks.

Regarding timing: https://github.com/rethinkdb/rethinkdb/issues/3711#issuecomment-169460842

**Comment by mattkrick** [comment]
Yeah, it's still a young spec and needs a little more work, especially on
error handling, but overall it's pretty great and a LOT simpler than
bloggers make it seem. Relay is the piece that needs the bulk of the change.

**Comment by mattkrick** [comment]
After reviewing deepstream it doesn't look flexible enough for what I want to do here. Deepstream is a really cool idea & I could see myself using it in another project, but the client cache & server are tightly coupled & non-extensible. I'm holding out for a solution that let's me use a redux store as a cache.

**Comment by abastardi** [comment]
> After reviewing deepstream it doesn't look flexible enough for what I want to do here. Deepstream is a really cool idea & I could see myself using it in another project, but the client cache & server are tightly coupled & non-extensible.

Got it. Have you considered adding SocketCluster compatible RPC functionality, such as [avs-rpc](https://github.com/gigerlin/rpc)?
