### ISSUE TITLE
Client cache options

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/meatier#45]
Client caching is painful right now.

Requirements:
- Uses redux store
- Offers offline-first experience

Nice-to-haves:
- webworkers
- Uses graphQL schemas

Problems:
- How does the store look? Most graphQL solutions (Relay, Adrenaline, Lokka) normalize data according to the graphQL schema. This is great unless you have subscriptions via websockets, then it doesn't know where to put the data. Something like minimongo that looks like the database seems easier, but writing code to covert graphQL schemas back into database-normalized wouldn't be great

-  The current solution works well & allows for a ton of flexibility, but complex graphQL queries would have to be digested & dispatch n+1 actions where  n is the number of tables the queries touches. This isn't the end of the world, but makes for large amounts of reducer boilerplate.

**Comment by mattkrick** [comment]
https://www.youtube.com/watch?v=S2Hp_1jqpY8
https://github.com/janmonschke/diffsync
https://github.com/gritzko/swarm
https://github.com/dominictarr/scuttlebutt

**Comment by Bartekus** [comment]
What about local-sync?
https://github.com/TechnologyAdvice/local-sync

**Comment by mattkrick** [comment]
looks interesting, I'll dig into the SC tonight, thanks!

**Comment by Bartekus** [comment]
No problem and thank you for your hard work on this Matt, you are doing incredible service to react community even though you aim at meteor. 

Also, as a side note, I'm not a big fan of modern ui let alone react-starter-kit (kriasoft does not follow community guidance hence create a lot of confusion for new comers, but that's just my opinion).

Anyway, I'll be integrating your meatier with opencredo-react-boilerplate, then dropping kanban out of it and concentrate only on providing a fully functional backend/users/admin logins, similar or 'rails-like' skeleton for public use. This is done with Anonymous in mind and would be rebranded to R3Stack with full credit due to you and meatier.
Is that ok by you?

**Comment by mattkrick** [comment]
sounds cool, yeah it's MIT so have a blast. I still don't like the necessity of creating a reducer for each database table, but aside from that I think the stack is just about done. What do you mean "done with Anonymous in mind"?

**Comment by Bartekus** [comment]
Thats excellent, I've got much to digest to fully understand the whole build, but so far I find your code to be very concise and in general very pleasurable to work with, all in all, I can't thank you enough Matt... 
As to what I mean, I like more kids to get involved in programming so I'm using the Anon movement (which I love dearly/tho I'm not part of it anymore) to spark and reinvigorate interest in programming thru web development in general but positive way, [at the moment the opposite is happening, destruction over creation :( and as somebody that enjoys conversations and philosophical discussions I'm not an keen fan of that], so I intend to change that. 
Just like rails lowered the entry barrier to allow gentle entry into an ever progressive field, so is the point of this undertaking. 
I believe every kid on this planet should be able to spin up their site overnight and express their personalities, creativity and wit. They should be given the best possible guidance and tools to fuel their magnificent minds...
I might be a dreamer, but you know, being one yourself, we are not alone and the world can be change thru positive dialog more so than any D.O.S or coordinated disruption attacks ever will for that matter. 

“No matter what people tell you, words and ideas can change the world.”
 - Robin Williams quotes

“To the world you may be just one person, but to one person you may be the world.”
 - Brandi Snyder

You might not see the impact you are creating yet, but I assure you the impact we leave by doing things we love... well... that makes all the difference... that can make you immortal in the minds of the generations to come.

Anyway, I'm raving here... you get the idea so once more thank you my friend, I'll keep you posted on all things and contribute in anyway that I can once I catch up with the build itself.

**Comment by mattkrick** [comment]
Sounds great, keep me posted on the progress. Depending on how far you take it, it make just make sense to transform meatier into your stack, although with how fast this stuff is changing, I don't think any stack is going to have the sticking power that LAMP had... with so many combinations a stack is basically whatever your package.json is.

I only dropped the kanban in there to give myself a good 1:M relationship between 2 tables to work with (a 1-table todo list doesn't do a great job of showcasing how to handling relationships). Now that the folder hierarchy is modular, it should be as easy as deleting the kanban folder to get started.

**Comment by Bartekus** [comment]
Ok I've set things in motion now and started to assemble the core group under araphel.org organization [established for oversight of OSI projects in general] to which I've send you the invitation now. 
Currently the group is empty and has only one little project under it, but it shouldn't interfere with the primary objective, r3stack. Furthermore, r3stack.com has been secured, logo has been made and now I've started to go thru your guide and also assembling general documentation as I'm going step by step over all aspects of the build trying to spot all the facets that could cause problem for inexperienced mind. I've also send-out proposals for cooperation to few parties, OpenCredo and Ipselon (creator of Structor) being the primary goals now to bring on board with us.

Some of the things that we'll need to decide is the most straightforward way to instal/operate and deploy the stack - being that the entry level should be as low as possible. 
Currently Docker is the most well-known choice, however there is also azk.io (also build on docker) which could potentially make it even easier and enable a single entry install. I believe that it could be potentially very powerful feature but I'd like you to also check it out and let me know what you think... 

I hear what you are saying in terms of LAMP and while yes, the rate of change is quite dramatic I believe that while we are a fully fledge framework now, we will take a different approach than frameworks do. ie we will not lend ourselves to be ridged and unchanging but rather we shall make continual evolution [as per best practices and general potential available from the community] our modus-operandi.
 
Our primary aim and general goal is to facilitate the best learning structure and experience for kids to gain an insights into the best practices and features currently available. This of-course will be moving target as the community evolves so will we, doing our best to reflect these changes as they appear - always attempting to provide the best solution using the best tools available.
 
I'm also a big fan of functional programing which I've observed you seem to favor as well (correct me if I'm wrong) so I think we should emphasis that aspect of JavaScript in general, at least when it makes the most sense. Obviously it's all situational so yeah, we'll adapt as we go with it.

In conclusion I think that by setting a standard that is reflective of the community's work, and which is evolving with the community, we can provide the best ground for insightful learning thru observation and reverse-engineering, which I think will appeal to most young minds eager to learn programming.

Furthermore we can bring a little bit of balance to otherwise very fractured and disjoined community and support all the good projects and practices while discouraging and discarding ineffective ones. 

The general structure of Araphel will be that of a conclave/philosophical branch of the anonymous movement and itself will be conducted as a round table, where each member is equal one another, and does his best to express and contribute in whatever capacity they can while at the same time setting an example and nurturing community in general. We will essentially create 'by hackers for hacker' kind of framework that encourages curious young minds to explore it by building, breaking, modifying and otherwise playing with it any way they see fit as they are making it their own.

I think the slogan that you devise is the best motto that reflects the nature of this undertaking:
React, Redux, Rethink...

Thats all for now, let me know what you think :D

**Comment by mattkrick** [comment]
Dang you work fast! A couple immediate thoughts:
Docker sounds good, although I have no experience with azk. Devops is
always a pain and can hopefully be ignored while training kids, but talking
about a required maintained state/ sticky sessions should be brought up
early so they keep it in the back of their minds.

The whole JS community is moving towards FP, which is good, but there's
still a place for OOP that should be addressed, I'd focus more on
minimizing side effects than staying purely functional. It'd also be nice
to discuss why immutability is slower per operation, but holistically
faster.

Another fun thing for me was learning about bcrypt and how it builds the
salt into the hash, for the security minded that's just cool. Also worth
getting everyone a copy of ettercap and wire shark and showing them how
easy it is to sniff a packet. IMHO this should be taught day #1 to all web
devs, the internet would be a lot safer place if that were the case...

As for the politics of the group, I'm sure you have way more experience in
what works for the demographic so I'll trust you lead on that. Looking
forward to what this becomes!

**Comment by Bartekus** [comment]
Sorry Matt, I haven't been able to do much progress today as I've got swamped at work last night and just finish :( I'm gonna grab some sleep and start early tomorrow.

However I do agree with you about Wireshark, it really open peoples eyes once they see how unencrypted stuff just swims in the air in full few. As to brcypt,, I can't say enough of good things about developers who are security conscious and understand the significance of such incredible and useful tools. 

Tho I've mention it yesterday I haven't shown you the little logo for r3stack, so before I go hit the hay, here it is... oh and yesterday I started to dockerize the meatier tho sadly I was interrupted with an emergency... but tomorrow! The objective will be to have it deployed :D

**Comment by Bartekus** [comment]
![r3stack](https://cloud.githubusercontent.com/assets/7887446/12470685/7639e38a-bfb3-11e5-8ad2-921863ee8697.png)

Opss... almost forgot... hehe

**Comment by mattkrick** [comment]
siiiick, looks awesome! I wish there'd be a way to sneak in the little rethinkDB guy, but a fluffy little marshmallow would probably kill the whole edgy modern look. :yum:

**Comment by Bartekus** [comment]
Hey THATS a great idea Matt! 
In fact, damn, consider it done... now that I think of it, it's a perfect mascot/logo! I don't thin it's gonna kill the edge at all, beside the RDB marshmallow guy just looks awesome and just like Mozilla with their cool Fox, we'll have a little cute critter to to make people who came for performance, stay for the personality and cuteness of it! Also I was talking to one of my colleagues about this and we came to conclusion that this has a rails-like potential at the moment, I gotta diligently rush dockerization process so is can be put on market in most easy way as soon as possible... I'll get up early tomorrow and get the logo infuzed with awesome cuteness.... just look at this cool guy, I love, great idea again Matt: 
![rethinkdb-pet](https://cloud.githubusercontent.com/assets/7887446/12471109/91b6019e-bfb7-11e5-9fa8-eac6cadcae03.png)

Pure win! Kids gonna love it, and if they identify with the mascot then right of the bat, they are much more likely to be interested in wanting to program to simply because they can identify with something that's tangible and meaningful to them!

**Comment by Bartekus** [comment]
Tomorrow RD-a-B-y is gonna swim with his buddy: 
![docker](https://cloud.githubusercontent.com/assets/7887446/12471149/1aef7882-bfb8-11e5-8d49-61818bafcdce.png)

**Comment by mattkrick** [comment]
>make people who came for performance, stay for the personality and cuteness of it! 

hahaha oh man, that' sounds awesome! Seriously, I think he's even cuter than the hipmunk or octocat. It's seriously a treat every time I visit the RethinkDB API.

**Comment by Bartekus** [comment]
I absolutely agree with you, rdaby-boy is gonna win people over with his cuteness and performance is just an icing on the cake! Making everybody smile while getting stuff done is the way of rdaby-boy!
Ok I'm jetting to bed, gotta make this happen early morning tomorrow... damn, I'm actually excited like a kid myself lol :D
Good night!

**Comment by mattkrick** [comment]
whaaa where'd that name come from? I thought he was "the thinker" http://annie-ruygt.squarespace.com/blog/2015/3/12/uktt673n0teivjklu8g4x0bgrl4ymv

**Comment by Bartekus** [comment]
You are probably right because I just made that name up lol

**Comment by mattkrick** [comment]
hahaha i like it!

**Comment by Bartekus** [comment]
We can nickname him that!

**Comment by Bartekus** [comment]
I'm looking into azk.io now as it seems to be exactly what we want to use to create single entry into development with r3 but at the moment the main problem is:
babel-plugin-add-module-exports

This module is used to technically restore Babel5 behavior in terms of babel-plugin-transform-es2015-modules-commonjs not supporting module.exports

Now to my knowledge and as far as I can see it being used in this build, its purpose is to facilitate webpack's treeshaking and dead-code elimination capability, however please do correct me if that's not its entire scope of its function.

If it is however, could we not all together forsaken modules-commonjs and use babel-preset-es2015-native-modules made as per Dr. Axel Rauschmayer [article] (http://www.2ality.com/2015/12/webpack-tree-shaking.html) and specifications:
```
module.exports = {
	plugins: [
		'transform-es2015-template-literals',
		'transform-es2015-literals',
		'transform-es2015-function-name',
		'transform-es2015-arrow-functions',
		'transform-es2015-block-scoped-functions',
		'transform-es2015-classes',
		'transform-es2015-object-super',
		'transform-es2015-shorthand-properties',
		'transform-es2015-computed-properties',
		'transform-es2015-for-of',
		'transform-es2015-sticky-regex',
		'transform-es2015-unicode-regex',
		'check-es2015-constants',
		'transform-es2015-spread',
		'transform-es2015-parameters',
		'transform-es2015-destructuring',
		'transform-es2015-block-scoping',
		'transform-es2015-typeof-symbol',
		['transform-regenerator', { async: false, asyncGenerators: false }],
	],
};
```

Which btw, you have jurisdiction over since it's released under Araphel:
[babel-preset-es2015-native-modules](https://github.com/Araphel/babel-preset-es2015-native-modules)

Please let me know!

**Comment by mattkrick** [comment]
>Now to my knowledge and as far as I can see it being used in this build, its purpose is to facilitate webpack's treeshaking and dead-code elimination capability, however please do correct me if that's not its entire scope of its function.

To my knowledge, it's got nothing to do with that. It's used so I can write `require('foo')` instead of `require('foo').default` since babel6 now exports default as a prop to keep folks from pulling props out of exported objects:
```
// index.js
export default  {a: 'b'}

import {a} from 'index.js' //invalid ES6, but legit in babel5
```

what's the problem it's causing?

**Comment by Bartekus** [comment]
So at the moment it seem that the package is either not properly registered with npm, azk doesnt like alpha modules (we'll test that as the r3stack is in alpha itself) or the problem is elsewhere.
This is the error that halts the whole thing:

azk: npm ERR! No compatible version found: babel-plugin-add-module-exports@0.1.3-alpha

I'll post the build into araphel now so we both can look at the same source as we are transitioning it into a r3stack.

So the only requirement with r3stack will be to have azk.io installed (it's really just neat VirtualBox agent in OSX, and docker agent in linux... they are working on windows version too but given that it's docker based, it's just a matter of time before they do... Then it's pure win since it will allow r3stack to have the similar ease of operation as rails do. 
Here is the link http://docs.azk.io/en/installation/

But if you have have brew it's as simple as:
```
brew update
brew upgrade 
brew install azukiapp/azk/azk
```
or one liner: (gotta love 'em :D )
```
brew update && brew upgrade && brew install azukiapp/azk/azk
```

after that from the r3stack dir try:
```
azk start -o && azk logs --follow
```
You might have to use 'azk init' first, but I'm fairly certain that is not needed given that r3stack has the proper config file already generated.

Let me know how it goes.

**Comment by mattkrick** [comment]
hmm, have you tried manually bumped it back to 0.1.2? Seems odd...

**Comment by Bartekus** [comment]
lol that worked, but now there is another problem:
```
azk: Error: HTTP code is 404 which indicates error: no such container - Cannot start container 7fd8767dd3966b266c1bbf52b990cdf08678fa6daf8a775beb9d7532d3230d05: [8] System error: exec: "npm run quickstart": executable file not found in $PATH

azk:     at /usr/local/Cellar/azk/0.16.3/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:218:17
azk:     at getCause (/usr/local/Cellar/azk/0.16.3/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:246:7)
azk:     at [object Object].Modem.buildPayload (/usr/local/Cellar/azk/0.16.3/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:217:5)
azk:     at IncomingMessage.<anonymous> (/usr/local/Cellar/azk/0.16.3/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:193:14)
azk:     at IncomingMessage.emit (events.js:117:20)
azk:     at _stream_readable.js:944:16
azk:     at process._tickCallback (node.js:448:13)
```
However this one has most likely something to do with azk so I'm opening a support ticket. But we are getting close :D

**Comment by mattkrick** [comment]
the guy deleted the 0.1.3-alpha from npm... i didn't think anyone still did that. 

i dunno what's up with that container error, where is the current $PATH? may have something to do with relative/absolute references in the package.json?

**Comment by Bartekus** [comment]
That's my local machine's problem, I'm going thru all my setting to make sure it's not misconfigured anywhere. Just went thru my .bashrc & .zshrc and fix few things that weren't 100% kosher, then did brew doctor and got a report with docker-tools which I still had old version of so had to shut down virtualbox and upgrade it, this was pretty [helpful](https://michaelheap.com/docker-machine-on-osx)
However the last part:
> eval “$(docker-machine env docker)”

is not going thru so I'm investigating, all along I'm trying to collect all the diagnostic info as it might be helpful to assemble it all into a help file for better support down the road. So it going, another hour and I should be back on track.

**Comment by Bartekus** [comment]
ok got past that, and all I really did is run virtualbox help which started the gui modal that informed that there is an upgrade, but when I said go ahead install it, turns out it was old so it said faild and quit, but >eval $(docker-machine env docker)

worked after that and so docker is fully operational now in conjunction with virtualbox.... last part of the puzzle, brew doctor still reports unlinked docker-machine and vim so I'll link them and test again to make sure that doesnt break what I fix so far :D oh boy, I mostly love and sometimes hate devops at the same time lol

**Comment by Bartekus** [comment]
ok, turns out I really did fix my problems on this machine, everything good now... except
damn NVM! lol 
https://github.com/creationix/nvm/issues/855 

added 
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
```
to my .zshrc && .bashrc 

then restart my shell and got:
```
nvm is not compatible with the npm config "prefix" option: currently set to "/Users/Bart/npm"
Run `npm config delete prefix` or `nvm use --delete-prefix v5.0.0 --silent` to unset it.
```
seems obvious what needs to be dont but just to be sure:
>nvm deactivate ; nvm debug ; echo $PREFIX ; echo $NPM_CONFIG_PREFIX

```
Could not find /Users/Bart/.nvm/*/bin in $PATH
Could not find /Users/Bart/.nvm/*/share/man in $MANPATH
$SHELL: /bin/zsh
$NVM_DIR: '$HOME/.nvm'
$PREFIX: ''
$NPM_CONFIG_PREFIX: ''
nvm current: system
which node: /usr/local/bin/node
which iojs: iojs not found
which npm: /usr/local/bin/npm
npm config get prefix: $HOME/npm
npm root -g: $HOME/npm/lib/node_modules
```
ok now we go with 
>nvm use --delete-prefix v5.0.0 --silent

then we check it:
>nvm deactivate ; nvm debug ; echo $PREFIX ; echo $NPM_CONFIG_PREFIX

```
/Users/Bart/.nvm/*/bin removed from $PATH
/Users/Bart/.nvm/*/share/man removed from $MANPATH
$SHELL: /bin/zsh
$NVM_DIR: '$HOME/.nvm'
$PREFIX: ''
$NPM_CONFIG_PREFIX: ''
nvm current: system
which node: /usr/local/bin/node
which iojs: iojs not found
which npm: /usr/local/bin/npm
npm config get prefix: /usr/local
npm root -g: /usr/local/lib/node_modules
```

gonna restart and then see whats up...

**Comment by mattkrick** [comment]
You try n instead of nvm?

**Comment by jeffreywescott** [comment]
It seems this conversation has wandered FAR off from "caching options". ;-)

**Comment by mattkrick** [comment]
@jeffreywescott haha yeah... blame @Bartekus :wink: probably easier to start a new thread now, but I'm still digging into it. I think I'm gonna have to write my own, which is lame. Digging more into relay it is one of the ugliest most convoluted APIs I've ever seen, but the power it offers is amazing. I think a lot of the complexity comes from being built on Flux (no middleware) and trying to do too much. For example, it handles the Loading, Error, and Result component. IMO it should pass those as props to the child it wraps & let the component itself decide how to handle the V in MVC, right now it's trying doing all 3 parts. It also makes you explicitly write out what the optimistic result would be... This is really brittle because state outside of relay might be based off the result. 

There are some parts like the build-in `pageInfo` that are great answers to problems that have plagued web devs for years (eg are there more records?). Hopefully I can come up with something a little more powerful than Lokka with a cleaner API than relay, we'll see what happens this weekend!

**Comment by Bartekus** [comment]
Sorry Matt, I've been away from the internet since Friday since there was an outage here in Edmonton :( Anyway, as I was cut off from the world I begun work on the front end and while I still got ways to go, in conjunction with azk, I'm making some headway. I'll keep you posted and show some results later on today. Also, congrats on almost 500 stars, I knew this is going to be popular, just wait till we make it ultra easy for anybody to launch and play with it, then it's just gonna sky-rocket! :D

**Comment by Bartekus** [comment]
Also don't blame me, I'm innocent :P lol

**Comment by mattkrick** [comment]
Haga no worries, i live in mexico, I know all about internet outages. Cut a
guy off from stack overflow and github and it makes him a much better
programmer though, I'll say that much!
... That said, client caching is a really hard problem to solve, internet
or no. It's gonna take me another week just to figure out I'd it's feasible
to do without packaging graphql on the client.

**Comment by ansarizafar** [comment]
@mattkrick  Please try to create GraphQL client with cache as a separate package without React or Redux dependency so that It can be used with other front end frameworks like Aurelia.

**Comment by mattkrick** [comment]
@ansarizafar it's gonna have a hard redux dep, which can be used with whatever. I love competition among front end frameworks, but just try & build meatier in aurelia... your initial client download is gonna be a monster. It still doesn't offer SSR (let alone streaming SSR), and async routing is...well, non existent last time i checked in on it.

That said, I totally agree the cache should be *View* layer agnostic (redux is in the model layer). Doing it this way opens up the door to neat things like predictive fetching (eg hover over a "get more" button & it starts downloading the results to the client cache)... but i've said too much :wink:

**Comment by abastardi** [comment]
Based on what you've built and learned, you might be interested in contributing to the discussion of Meteor's proposed new Reactive GraphQL data system: https://forums.meteor.com/t/reactive-graphql/17048

**Comment by mattkrick** [comment]
@abastardi It appears they haven't given the client cache any thought. Either they have to send graphQL + the entire introspection query to the client (HUGE payload) or they have to do what relay does & statically analyze the queries in a babel preprocessing step. The latter is the right way to do it, but it means exposing babel to the developer, which they still don't do in v1.3, right? I'll wait to see a developer preview before I pass judgement...

Out of curiosity, if facebook gives you your front end, your client cache, and your database connection, what is the value add for meteor? User Accounts?

**Comment by Bartekus** [comment]
Hehe seems to me they want to walk into the hell paved with facebook's good intentions... Personally seeing what FB does in India with their attempt at recreating internet in facebook's image, I'm rather hesitant to completely buy into what they are selling :/

**Comment by mattkrick** [comment]
Facebook's business practices are atrocious. They read your texts, they track your movements, they watch you browse the web. To do so, they need to attract top talent. They do that by being a pillar in the OSS community. It's a damn shame that the brightest minds in the world are wasted on generating ad revenue, but at least some good comes out of it (namely react). I interviewed with a company that puts data miners inside browser extensions. Shady as fuck, but you'd get to solve the coolest big data problems you've ever seen...

**Comment by mattkrick** [comment]
@Bartekus oh dammit there you go getting me off topic again... CLIENT CACHE CLIENT CACHE. haha worst github issue ever :frowning:

**Comment by Bartekus** [comment]
bartekus@gmail.com, let's take r3 convo into email/araphel repo :D
:+1:

**Comment by Bartekus** [comment]
@mattkrick ok convo is open under r3 in araphel, do you want me to migrate all the stuff from here there as to clean up this lane as it ought to be issue related? Also fire me an email so we can be in touch thru that as well

**Comment by mattkrick** [comment]
You can move comments from issues to other repos??? I mean, it doesnt really bother me, but I kinda wanna see that now...

**Comment by Bartekus** [comment]
Well manually that is :)

**Comment by mattkrick** [comment]
:+1:

**Comment by ansarizafar** [comment]
@mattkrick Please visit the link to see the reply of @EisenbergEffect about Aurelia and Async routing https://github.com/aurelia/skeleton-navigation/issues/41#issuecomment-175034024

**Comment by mattkrick** [comment]
@ansarizafar that's not async routing as far as I'm concerned. When I say async routing, I mean triggering a module to download on route change. Effectively, it's turning a SPA back into a payload-per-route website, the only difference is the payloads are a LOT smaller (but require JS to be enabled). If you have an example of aurelia serving up a page via SSR and then downloading additional routes as tiny javascript fetches (including images, fonts, css, whatever), I'd love to see it. Until then, it can't really compete...

**Comment by ansarizafar** [comment]
@mattkrick I have used async routing with React-Router and Webpack, Its really amazing. Currently I am  exploring other Front end frameworks. The ideas behind Aurelia are wonderful. Aurelia is in beta and we can't compare it with React at the moment though performance is already better then other frameworks according to this official blog post http://blog.durandal.io/2015/12/17/more-aurelia-performance-bug-fixes-docs-and-typescript-awesome/. Aurelia loader for webpack is not available at the moment. I am not sure how async routing will work with webpack that's why I asked Rob Eisenberg about it. He has also mentioned that Aurelia will have SSR.

**Comment by mattkrick** [comment]
For sure, I'm all about new tech that solves real problems & it's very true that people blindly swallow whatever facebook feeds them, so something outside the facebook (or google) ecosystem is always nice!  That said, async routing & SSR was a hard requirement when building meatier. If aurelia can provide a solid community ecosystem with things comparable to material-ui, react-dnd, and graphiql, react-dom-stream, etc. I'm all for it! IMO, picking a frontend based solely on performance is a really dangerous form of premature optimization, since performance is easier to fix than the community.

**Comment by ansarizafar** [comment]
You are absolutely right. Aurelia Interface is a collection of Custom HTML Elements which can be used to build applications http://blog.durandal.io/2015/11/20/aurelia-beta-week-day-5-aurelia-interface/.  I have found this few months old video in which Rob Eisenberg explaining ideas behind Aurelia https://channel9.msdn.com/Events/Seth-on-the-Road/DevIntersection-2015/Rob-Eisenberg-on-Aurelia

**Comment by EisenbergEffect** [comment]
If you guys have Aurelia questions, I invite you to our gitter room: gitter.im/aurelia/discuss You can also post issues on our repos on github. Let's not crowd this issue with Aurelia-specific discussion. I'm not sure the meatier team would benefit from that.

**Comment by jeffreywescott** [comment]
@mattkrick, since no one seems to want to talk about caching, but instead wants to talk about meatier in general, perhaps meatier needs its own gitter?

**Comment by mattkrick** [comment]
@jeffreywescott no kidding, I need to sit down & actually write cashay (the new client cache) so I can close this issue and keep it clean :smile: The gitter badge is the first thing you see in the readme... i think i need a bigger badge!

**Comment by jeffreywescott** [comment]
Maybe close and re-open this issue to re-focus it on caching, then encourage people to go to gitter?
