### ISSUE TITLE
Only works in Chrome browser

### ISSUE THREAD

**Issue by peteflanagan** [mattkrick/meatier#6]
The application is not visible in Firefox or Safari.  Inspecting in Firefox reveals that the page returned a 200 OK status but the screen is blank.  I notice the same behavior in Safari.

**Comment by mattkrick** [comment]
Nice catch, it's because I'm not transpiling Joi in the `node_modules` folder in the webpack build.
This makes HMR faster for development, but only works for the latest browsers (Chrome, Chrome Canary, Firefox Nightly, Webkit Nightly).

As a fix, crack open the webkit config & swap out the `include` line with this:
`include: [path.join(root, 'src', 'client'), path.join(root, 'src', 'universal'), path.join(root, 'node_modules', 'joi')],`

The root cause is the maintainer of Joi stubbornly refusing to publish an ES5 compatible build (despite everybody wanting it & every other package on NPM doing it). If you find this annoying, wouldn't hurt to voice your opinion: https://github.com/hapijs/joi/issues/528
Maybe I'll fork the project just to post a transpiled version on npm :smile:
