### ISSUE TITLE
Deploying a Meatier application

### ISSUE THREAD

**Issue by patrickleet** [mattkrick/meatier#60]
How would one go about deploying a production version of a Meatier application? 

~~Does socket cluster need to run on a separate server? Can it be configured?~~
K, got confused because I saw it IS possible.

~~What about RethinkDB? The config seems to be hardcoded to localhost~~ 
Duplicate of #52 
See progress being made with the azk branch linked to in that thread. 

I made a landing page with meatier and am not really sure how to put it up now!

**Comment by mattkrick** [comment]
We're still working towards simplifying dev ops, for now the link you found to https://github.com/Araphel/meatier is the best starting point. Deployment is really no harder than any other SPA, but it's never gonna achieve 1 click deployment since this is targeted towards advanced applications that need more power than what simpler solutions offer.
