### ISSUE TITLE
Use Redux Devtools Extension instead of keeping unnecessary boilerplate and dependencies 

### ISSUE THREAD

**Issue by alanrsoares** [mattkrick/meatier#68]
* Use [Redux DevTools Extension](https://github.com/zalmoxisus/redux-devtools-extension)

cc @mattkrick

**Comment by Bartekus** [comment]
At the moment 'Redux Devtools Extension' is only applicable to Chrome users, so leaving out the rest is probably not the best way to save few lines of code. Beside the only dependencies that devtools use are:
```
"redux-devtools": "3.1.1",
 "redux-devtools-dock-monitor": "1.0.1",
 "redux-devtools-log-monitor": "1.0.4",
```
That's hardly taxing, wouldn't you say?

**Comment by alanrsoares** [comment]
@Bartekus, you've got a point. 
Compared to the already huge number of dependencies, three more aren't that scary.

**Comment by Bartekus** [comment]
Oh @alanrsoares ;) you also got a point about huge number of dependencies, but given that meatier imitates meteor, which itself is a framework, I think that's unavoidable. Perhaps I'll look into slim-fasting the dependencies since few of them can definitely go, as to devDependencies, well that's a different story but also one of lesser concern IMO.

**Comment by mattkrick** [comment]
It's tough to keep a minimal dev stack and offer a super slim prod stack. I
love all the niceties of developing super fast, but pushing a 5Kb paint to
the prod client takes priority. Anything that can help achieve the goal is
always welcomed :-)

**Comment by wmertens** [comment]
That said, it is trivial to support the devtools extension: https://github.com/zalmoxisus/redux-devtools-extension/commit/6c146a2e16da79fefdc0e3e33f188d4ee6667341 so it would be cool if that was supported by meatier

**Comment by mattkrick** [comment]
haven't had time to play with this, but does it give back screen real estate by putting stuff in a separate window? If so, I'm sold. For heavy devving I think it's OK to expect a certain browser, I do that already since safari's version of webkit can't (or didn't) handle `const` and instead of increasing build times I just assume a browser that can handle it natively. 

PS what's up with the roadmap having a firefox extension? I thought firefox was on their way to being compatible with chrome extensions?

**Comment by wmertens** [comment]
Yes, it puts the inspector panel in either a separate window or in the devtools pane, and even better, you can inspect production code, since it only injects the tools on request.

No idea about the FF extension though...
