### ISSUE TITLE
Support MongoDB

### ISSUE THREAD

**Issue by wmertens** [mattkrick/meatier#71]
The readme seems to imply that using MongoDB instead of RethinkDB is not hard.

Is that correct, and if so, what would be the work involved?

**Comment by mattkrick** [comment]
GraphQL sits in what I'll call the "data transformation" layer, making a DB switch really easy. Basically you just have to change the resolve functions & use a mongo driver instead of a rethinkdb driver & you're all set. 1 hour tops. 

Where things get a little dicey is how you handle subs. Postgres has NOTIFY, mongo has the oplog, etc. But, if you come from the meteor community, you know the pitfalls of oplog tailing & if you're leaving meteor for scaling reasons, chances are that's not a viable solution. RethinkDB is nice since it handles pubsub very efficiently without the need for a replica, rabbitmq, or redis. A best practice (or even a final spec) hasn't emerged yet for subs in GraphQL. But my guess is things are headed towards event-based subs. See http://hueypetersen.com/posts/2015/10/28/experimenting-with-graphql-subscriptions/ for a good example.

**Comment by wenzowski** [comment]
@wmertens Looks like you could just drop something like [mongo-oplog](https://github.com/cayasso/mongo-oplog) in each [subscription](https://github.com/mattkrick/meatier/blob/master/src/server/graphql/models/Lanes/laneSubscription.js) noting that it's currently the presence of `old_val` and `new_val` that [determines the op on the client](https://github.com/mattkrick/meatier/blob/master/src/universal/modules/kanban/ducks/lanes.js#L112)

**Comment by mattkrick** [comment]
yep, i think this issue is solved. If not, feel free to reopen with specific reqs.

**Comment by jamesdwilson** [comment]
+1 for mongodb support. RethinkDB is too early to adopt I think. No free hosts, no software to browse the db.

**Comment by mattkrick** [comment]
@jamesdwilson localhost:8080 :wink:

**Comment by wmertens** [comment]
@jamesdwilson ...or is it? Check out the Jepsen reports on RethinkDB and
MongoDB…

https://aphyr.com/posts/330-jepsen-rethinkdb-2-2-3-reconfiguration

https://aphyr.com/posts/322-jepsen-mongodb-stale-reads

Food for thought…

**Comment by mattkrick** [comment]
When you invest in a company you don't invest in the idea, you invest in the team. Same goes for DBs.

Mongo closes issues claiming that things are working as designed, despite users begging for fixes 3 years later. RethinkDB answers your questions on stackoverflow late sunday night and builds features based on issues that pop up on their github.

WRT graph databases, the same goes for orientDB vs neo4j. Sure orient has some great ideas, but I'm not gonna support something that isn't in touch with its userbase.
