### ISSUE TITLE
Free automatic SSL certs using letsencrypt

### ISSUE THREAD

**Issue by patrickleet** [mattkrick/meatier#80]
I'm trying to play with this now, but not sure how it's affected by SocketCluster

https://www.npmjs.com/package/letsencrypt
https://github.com/Daplie/letsencrypt-express

Would be a nice addition!

**Comment by Bartekus** [comment]
That looks nice, what you think @mattkrick ? Looking at worker.js I can see how we could take advantage of this, but I'm not master of SocketCluster so I'm not 100% about this.

**Comment by mattkrick** [comment]
Oh I'm stoked someone brought this up! Yeah let's start with encrypting the
http server and then can do a separate PR for websockets, I can't remember
all the details about wss

**Comment by Bartekus** [comment]
Ok, I'll tackle this as soon as I finish with the webpack update... have you had a chance to look at the proposed npm script changes yet?

**Comment by mattkrick** [comment]
awesome, yep, checked it out & it looks really good, but I got sidetracked with a little redux side project

**Comment by Bartekus** [comment]
It's all good, gotta do what you gotta do Matt :)

**Comment by mattkrick** [comment]
I think this is outta scope of the project since it's more devops. 
BUT, I just did this using dokku on digital ocean & i'm blown away by how easy it is.
1. Install the plugin: https://github.com/dokku/dokku-letsencrypt
2. Run the plugin
3. make a renewal cron job: https://blog.semicolonsoftware.de/running-dokku-letsencrypt-auto-renewal-as-a-cronjob/
It occurs at the reverse proxy layer (nginx), not the application layer. That means there's no changes necessary for your app.
I still haven't done it for wss, will cross that bridge in the next few days.
