### ISSUE TITLE
Yeah!!! This is what I want, make it happen.

### ISSUE THREAD

**Issue by meepeek** [mattkrick/meatier#94]

**Comment by meepeek** [comment]
I think I can help you with user testing, article writing and documentation. Please let me know if it had become solid enough and if there were anything else I could help for the time being.

By the way, I presume that you had react-native in your mind already and the redux you mentioned, will it handle the server/client sync as well ? As a meteor user, I think this feature is really nice, having the system handle authentication with data layer integration.

**Comment by mattkrick** [comment]
server/client sync is an application level decision. If you need a realtime document update, use a subscription. If you've got a data req that will change infrequently, it makes more sense to use a query instead of a sub. if you need to do something like a document collaboration, you'll probably want a CRDT solution. Auth isn't given any special treatment, I just wrote an example production-ready example because it's something beginners frequently mess up, but the end example is a user document that ends up in your redux state. 

i'd love your help on test coverage if you're up for it. I wrote a couple example integration tests for the auth but pretty much every folder with a __tests__ subfolder should have a test or 2.

**Comment by Charuru** [comment]
This has potential to be huge... Meteor got like 100 mil in investments, keep at it and you'll be rich man.

**Comment by Bartekus** [comment]
Oh @Charuru, there is so much more to life than money... 
When you look back on your life one day, will you gauge success by the power that you attained and the wealth that you accumulated? Or, will you measure the degree to which your life was rich in character and purpose? Will it matter that you led an honorable existence, made a difference in people’s lives, and left the world a better place for your children? Albert Einstein said it well, “Not everything that can be counted counts, and not everything that counts can be counted.” The choice is yours. There’s more to life than money my friend.

**Comment by jeffreywescott** [comment]
I like you, @Bartekus. :-)

**Comment by Bartekus** [comment]
The feeling is mutual @jeffreywescott, we're all in this together :)
